apiVersion: v1
kind: ConfigMap
metadata:
  name: ensa-api-config
  namespace: ensa-investor-prod
data:
  SPRING_PROFILES_ACTIVE: "prod"
  MYSQL_DATABASE: "railway"
  MYSQL_HOST: "${RAILWAY_PRIVATE_DOMAIN}"
  MYSQL_PORT: "3306"
  MYSQL_USER: "root"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  SMTP_HOST: "smtp.office365.com"
  SMTP_PORT: "587"
  CORS_ORIGINS: "https://investidor.ensa.co.ao,https://www.ensa.co.ao"
